input_data: # INPUT DATA
  # Base model input for v19 and v20
  BaseT1_v20 : "select * from mssql.calculo_sitio_v20_t1"
  BaseT2_v20 : "select * from mssql.calculo_sitio_v20_t2"
  BaseT1_v19 : "select * from pmn.carbono5_calculo_20140421_v19_t1"
  BaseT2_v19 : "select * from pmn.carbono5_calculo_20140421_v19_t2"

  # BUR input data
  AreasEstratos_BUR : "select cves,cves2_pmn,cves3_pmn,cves4_pmn from pmn.biomasa_areas_estratos_s2_s3_s4_s5"
  AreasEstratosPersistentes_BUR : "select * from pmn.dcarbono_areas_estratos_pmn"
  EstratoCong_biomasa_BUR : "select * from pmn.biomasa_estratos_cong_pmn_gus_s4"
  EstratoCong_BUR : "select * from pmn.carbono5_estrato_cong_pmn_gus_serie4_2"
  EstratoSitio_s4_s5_BUR : "select * from pmn.dcarbono_t_1234_pmn45"
  EstratosIPCC_BUR : "select * from pmn.estratos_pmn_ipcc"

  # MADMEX input data
  AreasEstratos_MADMEX : "select cves, madmex_05, inegi_s4 from madmex.v_areas_estratos"
  AreasEstratosPersistentes_MADMEX : "select madmex_05_10, areas_cves4_cves5_pmn from madmex.v_areas_estratos_persistent_lcc"
  EstratoCong_MADMEX : "select * from madmex.estrato_cong_pmn_gus_serie4_2_madmex_05_10"
  EstratosIPCC_MADMEX : "select * from madmex.v_estratos_madmex_ipcc"

  # FEFA report input data
  BaseCruces_BUR : "select * from r_error_prop.cruces_series_inegi"
  BaseDinamica_BUR : "select * from r_error_prop.dinamica_bur"
  #old static version
  #TablaFEdefor_BUR : "select * from r_error_prop.fe_deforestacion"
  #TablaFApermaP_BUR : "select * from r_error_prop.fe_permanencia"
  
  # dynamic version:
  TablaFEdefor_BUR : "select * from pmn.v_tablafedefor_bur"
  TablaFApermaP_BUR: "select * from pmn.v_TablaFApermaP_BUR"
  TablaFEdegra_BUR : "select * from r_error_prop.fe_degradacion"
  TablaFArecup_BUR : "select * from  r_error_prop.fe_recuperacion"

  BaseCruces_MADMEX : "select * from r_error_prop.cruces_series_inegi"
  BaseDinamica_MADMEX : "select * from r_error_prop.dinamica_bur"
  TablaFEdefor_MADMEX : "select * from r_error_prop.fe_deforestacion"
  TablaFEdegra_MADMEX : "select * from r_error_prop.fe_degradacion"
  TablaFArecup_MADMEX : "select * from  r_error_prop.fe_recuperacion"
  TablaFApermaP_MADMEX : "select * from r_error_prop.fe_permanencia"


results: # RESULT data set definition
  output_dir : /Volumes/SSD2go_tw/conafor/reporting/results
  db_schema : client_output
  base_model_version : 20
  metadata_table : client_output.fe_reports_metadata

db: # database connection
  host : reddbase.conabio.gob.mx
  name : reporting
  user : postgres
  pass : postgres.

db-aws:
  host : madmexdb.cugskh78cduk.us-west-1.rds.amazonaws.com
  name : reporting
  user : reporting
  pass : 

